#before_cache:
#  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
#  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    #- $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
sudo: required
services:
  - docker
dist: trusty
language: java
jdk:
  - oraclejdk8
#  - openjdk8
  - openjdk11
env:
  - GRADLE_OPTS="-Xmx512m -XX:MaxPermSize=256m"
script:
  - ./gradlew build jacocoTestReport
#after_success:
#  - bash <(curl -s https://codecov.io/bash)
before_deploy:
  - sudo apt install --only-upgrade docker-ce -y
  - echo "$ORG_GRADLE_PROJECT_docker_apiPassword" | docker login -u "$ORG_GRADLE_PROJECT_docker_apiUsername" --password-stdin
deploy:
  provider: script
#  script: scripts/tag-release.sh && scripts/publish-site-starter.sh && scripts/publish-docker-image.sh
  script: ./gradlew buildDocker
  skip_cleanup: true
  on:
    branch: master
    jdk: openjdk11
