name: Build with Gradle

on:
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload dependencies
        uses: actions/upload-artifact@master
        with:
          name: dependencies
          path: build/deps

      - name: Upload artefacts
        uses: actions/upload-artifact@master
        with:
          name: bundles
          path: build/libs

      - name: Upload extensions
        uses: actions/upload-artifact@master
        with:
          name: extensions
          path: build/extensions

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download dependencies
        uses: actions/download-artifact@master
        with:
          name: dependencies
          path: build/deps

      - uses: jakejarvis/s3-sync-action@master
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'ap-southeast-2'
          SOURCE_DIR: 'build/deps'
          DEST_DIR: "${GITHUB_REF##*/}/wp/deps"

      - name: Download artefacts
        uses: actions/download-artifact@master
        with:
          name: bundles
          path: build/libs

      - uses: jakejarvis/s3-sync-action@master
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'ap-southeast-2'
          SOURCE_DIR: 'build/libs'
          DEST_DIR: "${GITHUB_REF##*/}/wp/install"

      - name: Download extensions
        uses: actions/download-artifact@master
        with:
          name: extensions
          path: build/extensions

      - uses: jakejarvis/s3-sync-action@master
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'ap-southeast-2'
          SOURCE_DIR: 'build/extensions'
          DEST_DIR: "${GITHUB_REF##*/}/wp/extensions"
